### ISSUE TITLE
Missing GPG Key when installing github cli

### ISSUE THREAD

**Issue by DogaCUlupinar** [devcontainers/features#144]
**My Issue**
GPG signing issue within my codespace even after setting :
```
"features": {
		"ghcr.io/devcontainers/features/github-cli:1": {}
	},
```
I my devcontainer.json

in my script called within postCreateCommand it has a sudo apt update where i get the gpg error:
```
2022-09-07 21:11:53.429Z: W: GPG error: https://cli.github.com/packages stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23F3D4EA75716059
2022-09-07 21:11:53.429Z: E: The repository 'https://cli.github.com/packages stable InRelease' is not signed.
2022-09-07 21:11:53.433Z: N: Updating from such a repository can't be done securely, and is therefore disabled by default.
2022-09-07 21:11:53.434Z: N: See apt-secure(8) manpage for repository creation and user configuration details.
```

My dockerfile is based off of:
```
FROM mcr.microsoft.com/vscode/devcontainers/universal:2-focal
```

**Context**
I have been referred to create an issue in this project from https://github.com/cli/cli/issues/6175 by @joshspicer 

**Link To Original Comment I posted**
Original Issue: https://github.com/cli/cli/issues/6175#issuecomment-1239916118

**Comment by joshspicer** [comment]
The universal image includes the github-cli already, so that feature is actually no-oping.  

That said, I can't reproduce an _error_ in the kitchensink, only warnings (which is interesting).

<img width="810" alt="image" src="https://user-images.githubusercontent.com/23246594/189175930-49c7eea7-27bd-46ef-b9c3-960eb32235e7.png">

We cache copies of the image to keep Codespace creations fast, which is why this image is a bit behind.  Doing a rebuild (command palette `> Codespaces: Rebuild Container` of your codespace should pull the latest image, should get you the latest fixes!

**Comment by DogaCUlupinar** [comment]
Thanks @joshspicer the manual rebuild of the container worked!

**Comment by DogaCUlupinar** [comment]
@joshspicer I actually get the original error every time i create fresh codespace. I then have to rebuild the codespace for the issue to resolve. This happens with and without the features set so please let me know if i should file this ticket elsewhere, thanks!
