### ISSUE TITLE
Provide a feature that can install azure cli extensions

### ISSUE THREAD

**Issue by asaikali** [devcontainers/features#149]
I would like to be able to instal the azure cli and some extra extensions for example `az extension add --name spring` it would be nice to enhance the existing cli feature to set a list of extensions to install, or maybe add an azure cli extension feature that takes an array of extension names and installs them. 

The [blog post](https://dev.to/azure/extending-vscode-dev-container-features-4n71) show to build such a feature. However, installing azure cli extensions so common it should be officially supported.

**Comment by jkeech** [comment]
@asaikali thanks for the recommendation! Would you or @pauldotyu (the author of the linked blog post) be willing to submit a PR to add an `extensions` option to the `azure-cli` feature in this repo?

Note that we are tracking an improvement in https://github.com/devcontainers/spec/issues/91 which will make it easier for features to see which user is the `remoteUser`, so that you can easily run the extension installation command in the context of the correct user. It might be helpful to wait for that improvement to land first.
