### ISSUE TITLE
[github-cli] Race condition when checking for latest version

### ISSUE THREAD

**Issue by mislav** [devcontainers/features#259]
By default, `ghcr.io/devcontainers/features/github-cli` is configured to fetch and install the latest GitHub CLI version available.

However, it determines the latest release not by checking GitHub Releases in the `cli/cli` repository, but by scanning git tags in the same repository:
https://github.com/devcontainers/features/blob/73a9c7d38293067a4081b8d79dd12e92a585ef83/src/github-cli/install.sh#L168

This is wrong because a presence of a git tag does not guarantee presence of release assets (the script tries to download the `https://github.com/cli/cli/releases/download/v${CLI_VERSION}/gh_${CLI_VERSION}_linux_${arch}.deb` asset). Assets can only be downloaded from published Releases, not from git tags. Therefore, the script should check for published Releases in the `cli/cli` repository and ignore git tags.

Due to our release automation in the `cli/cli` repository, it can take 10–20 minutes between a git tag is published and the associated Release being published that contains all the compiled assets. During that time, this devcontainer feature is vulnerable:

```
2022-11-03 16:21:51.228Z: #14 0.678 Downloading github CLI...
2022-11-03 16:21:51.512Z: #14 1.068 CLI_VERSION=2.19.0
...
2022-11-03 16:21:51.624Z: #14 1.158 ... https://github.com/cli/cli/releases/download/v2.19.0/gh_2.19.0_linux_amd64.deb
...
2022-11-03 16:21:51.763Z: #14 1.265 HTTP request sent, awaiting response... 
2022-11-03 16:21:51.876Z: 404 Not Found
```

Thanks @tspascoal who ran into and reported this.

**Comment by jkeech** [comment]
Thanks for reporting. I think one issue is that switching to the Releases API could very quickly run into auth issues and rate limiting when un-authed. Using the git tags helps avoid rate limiting on the APIs since this is a public feature that can be used in Dev Containers without being signed in to GitHub locally.

Even if we can't use the Releases API directly due to auth/rate limiting issues, we could definitely make the tag lookup smarter by trying the latest and then walking backwards if the latest one fails, resulting in matching the most recent one that is fully uploaded.

**Comment by Chuxel** [comment]
Ideally the CLI repo would have a file in main with the list of current releases that we could parse for this.

But, yeah the release API is not an option due to rate limits but we can do a fallback. This is how the nix feature handles this.

https://github.com/devcontainers/features/blob/73a9c7d38293067a4081b8d79dd12e92a585ef83/src/nix/install.sh#L52-L62

Go does the same thing.  

There's a utility function here to make that work for nix we could reuse in other spots. https://github.com/devcontainers/features/blob/73a9c7d38293067a4081b8d79dd12e92a585ef83/src/nix/utils.sh#L268-L300

**Comment by samruddhikhandale** [comment]
Closing as completed with https://github.com/devcontainers/features/pull/310 🚀
