### ISSUE TITLE
Common Utils - If installing ZSH, set as default shell for user

### ISSUE THREAD

**Issue by jacobwoffenden** [devcontainers/features#324]
Hi,

When using the `common-utils` feature, and setting `installZsh` to `true` (default behaviour), I think it would be useful to change the default shell for the determined `${USERNAME}`. I've found that I either need to do it in `postCreateCommand` (e.g. `sudo chsh --shell /bin/zsh vscode`) or configure it via [Terminal Profiles](https://code.visualstudio.com/docs/terminal/profiles), although I haven't managed to get this working yet using [`customizations`](https://containers.dev/supporting#visual-studio-code)

**Comment by samruddhikhandale** [comment]
Hi @jacobwoffenden 👋 ,

As a heads up, we're discussing splitting up the `common-utils` Feature: https://github.com/devcontainers/features/issues/67 where we have discussed of creating a new feature for `Zsh`.

>  When using the common-utils feature, and setting installZsh to true (default behaviour), I think it would be useful to change the default shell for the determined ${USERNAME}

This is a good point and makes sense to me. However, making this change now could be a little disruptive for the users who expects `bash` as their default shell when they use this `common-utils` Feature. Also, most of the [dev container images](https://github.com/devcontainers/images) rely on this `common-utils` Feature. The community using these images have also been expecting `bash` as the default shell. We could add a command to change the shell to `bash` for the image but again it would be little contradictory.

I wonder if we could hold on making this change in https://github.com/devcontainers/features/pull/325 for now as it will be soon addressed by https://github.com/devcontainers/features/issues/67#issuecomment-1191525229? I can add this suggestion to ensure that `zsh` is configured for the default user when the `zsh` Feature is used. We could also add a new `isConfigured: true` property for the Feature so that anyone could disable and simply install `zsh`. (That'll be useful for the dev container images)

@jacobwoffenden what do you think?

**Comment by jacobwoffenden** [comment]
Hey @samruddhikhandale!

I'd come across https://github.com/devcontainers/features/issues/67 and I think it's a good idea, I just didn't know how long it would take to happen.

In light of your comments, I've updated my PR to move the `chsh` behind an option that defaults to false, would this be enough to get the change in for now and then potentially reused when the `zsh` feature is created

**Comment by samruddhikhandale** [comment]
> In light of your comments, I've updated my PR to move the chsh behind an option that defaults to false, would this be enough to get the change in for now and then potentially reused when the zsh feature is created?

✨ Yes! Yes! Looking 👀
