### ISSUE TITLE
Why not the node Feature installs the latest nvm by default?

### ISSUE THREAD

**Issue by eitsupi** [devcontainers/features#666]
Related to #190 and #194

Currently the default version of nvm is fixed at 10 months old `0.39.2` and does not appear to auto-detect the latest version.

https://github.com/devcontainers/features/blob/71ac2021e1350e673c0602b2ab6526d4353bc293/src/node/devcontainer-feature.json#L31-L35

Do you think we can automatically select the latest version here as is done in a smattering of other Features?

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for raising this question! 

By looking at the history of this Feature (especially when it was scripts), it seems like the `nvm` version has been pinned since the beginning. The only reason I could think of --> Pinning the NVM version helps avoid failures to the Node Feature with an upstream breaking or an error prone version of `nvm`. This is a good thing to have, however, the Feature ends up having stale NVM installed and it's adds maintenance cost. Also, with the switch to Features, if the upstream nvm breaks, one can always pin the older working version with `nvmVersion` option or the `devcontainers/maintainers` can temporarily pin the `default` to the working version.

Said that, I agree that supporting the `latest` version as `default` for `nvmVersion` makes sense to me! 👍 

// cc @Chuxel @joshspicer feel free to share your thoughts or correct my understanding
