### ISSUE TITLE
docker-in-docker: Feature does not automatically fix permissions

### ISSUE THREAD

**Issue by sr229** [devcontainers/features#678]
Currently using the dind feature would not fix permissions, which is troublesome for first time use. The feature should be able to infer automatically the user to enroll into the docker group.

![image](https://github.com/devcontainers/features/assets/14976516/3da12ffc-9bd2-4a9a-a089-0d1d4496432d)

**Comment by sr229** [comment]
> Hi 👋
> 
> @sr229 Can you help me repro steps and a sample dev container config? Also, what's the version of the `docker-in-docker` Feature that you are using? Thanks!

The repro steps should be easy, simply create a devcontainer.json file with the latest dind feature, like so:
```json
// For format details, see https://aka.ms/devcontainer.json.
{
  "name": "TestImage",
  "image": "mcr.microsoft.com/vscode/devcontainers/base:debian",
  "mounts": [ "source=/var/run/docker.sock,target=/var/run/docker.sock,type=bind" ],
  "features": {
    "ghcr.io/devcontainers/features/ruby:1": {},
    "ghcr.io/devcontainers/features/docker-in-docker:2": {},
    "ghcr.io/devcontainers/features/github-cli:1": {},
    "ghcr.io/devcontainers/features/node:1": {
      "version": "20"
    },
    "ghcr.io/devcontainers/features/common-utils:2": {
      "nonFreePackages": true,
      "upgradePackages": true
    }
  }
}
```

then simply run `docker info`.

**Comment by samruddhikhandale** [comment]
Hi 👋 

@sr229 are you trying to access `docker` which is available on the host machine? If that's the case, then can you use the [docker-outside-of-docker](https://github.com/devcontainers/features/tree/038bed3d58a84885da8a008b80905da17d57a543/src/docker-outside-of-docker) Feature instead? Also, remove the `"source=/var/run/docker.sock,target=/var/run/docker-host.sock,type=bind"` mount from your dev container because the Feature already adds that.

**Reasoning**: Docker-in-docker is a separate docker daemon inside of the main container, sort of like nested virtualization. It uses a totally separate /var/lib/docker directory that is not shared with the host. Docker-outside-of-docker is a different model however where the host’s docker socket is bind mounted into the container, so docker commands executed from inside the container actually execute on the host.

**Comment by sr229** [comment]
> Hi 👋
> 
> @sr229 are you trying to access `docker` which is available on the host machine? If that's the case, then can you use the [docker-outside-of-docker](https://github.com/devcontainers/features/tree/038bed3d58a84885da8a008b80905da17d57a543/src/docker-outside-of-docker) Feature instead? Also, remove the `"source=/var/run/docker.sock,target=/var/run/docker-host.sock,type=bind"` mount from your dev container because the Feature already adds that.
> 
> However, If that's not the case, and you are trying to simply create a new docker daemon within the container, then simply remove the `"source=/var/run/docker.sock,target=/var/run/docker.sock,type=bind"` volume mount.
> 
> **Reasoning**: Docker-in-docker is a separate docker daemon inside of the main container, sort of like nested virtualization. It uses a totally separate /var/lib/docker directory that is not shared with the host. Docker-outside-of-docker is a different model however where the host’s docker socket is bind mounted into the container, so docker commands executed from inside the container actually execute on the host.

I can confirm docker-outside-of-docker fixes this issue so I will close this instead.
