### ISSUE TITLE
[Bug] Oryx tool needs to be built with .NET 7

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/features#760]
From https://github.com/devcontainers/images/pull/855#issuecomment-1815369560
Blocks https://github.com/devcontainers/images/pull/855

> Oryx tool needs to be built with .NET 7, however, looking at https://github.com/devcontainers/images/actions/runs/6895550673/job/18760553721?pr=855#step:3:18052, it's getting built with .NET 8. This is definitely a bug in the [oryx Feature](https://github.com/devcontainers/features/tree/main/src/oryx) which needs to be fixed to unblock this PR.

**Comment by seesharprun** [comment]
I'm working on a PR (https://github.com/microsoft/Oryx/pull/2272) to see if we can get this limitation removed entirely.

The packages referenced in the **Directory.Build.props** file are causing the build error even if you have .NET 7 installed. The reason is because .NET 8 ships with newer versions of those packages and the build error is intentional to push people to upgrade and not leave critical packages locked to older versions.

**Comment by seesharprun** [comment]
I think we can consider this bug solved now, correct?

**Comment by samruddhikhandale** [comment]
Yep, oryx is now built with .NET 8. Thanks @seesharprun for https://github.com/microsoft/Oryx/pull/2272
